### ISSUE TITLE
[BR] Failed to join channel

### ISSUE THREAD

**Issue by walvering** [Levak/warfacebot#60]
erro: Filed to join channel {Invalid token or userid}

**Comment by Levak** [comment]
See #58 
Fixed with 204e667ba6ac2457745d8b9eb8b46ecf55f1b45b

**Comment by walvering** [comment]
Even with application of the new code ... it still continues with the same "bug" ... could quote an explo of how it would look

**Comment by Levak** [comment]
> Even with application of the new code ... 

Are you compiling from sources or using public release?
To apply this patch you need to recompile from sources (using `make`), as public release was not yet fixed (will be next week).

I cannot test on BR because they are region-locked, only BR can access their game servers.

**Comment by Levak** [comment]
Any news?

**Comment by walvering** [comment]
can not

**Comment by Levak** [comment]
> can not

Please answer to my above question.
> Are you compiling from sources or using public release?

**Comment by walvering** [comment]
yes

**Comment by Levak** [comment]
Then, try with the last automatic build from today:

https://github.com/Levak/warfacebot/releases/tag/1.0.8

**Comment by Levak** [comment]
Closing for no answer.
